export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-seller-email',
  CHANGE_PASSWORD: '/change-password',
  CATEGORY: '/categories/:categoryName',
  CATEGORY_SHIRTS: '/categories/shirts',
  CATEGORY_JEANS: '/categories/jeans',
  CATEGORY_SHOES: '/categories/shoes',
  CATEGORY_BAGS: '/categories/bags',
  LIVE: '/live',
  BUY_NOW: '/buy-now',
  ADDRESSES: '/addresses',
  NEW_ADDRESS: '/addresses/new',
  EDIT_ADDRESS: '/addresses/edit/:id',
  LISTING_PAGE: `/listings/:id`,
  NEW_PRODUCT: `/new-product`,
  ORDERS: '/orders',
  SALES: '/sales',
  YOUR_BIDS: '/bids',
  MANAGE_LISTINGS: '/manage-listings',
  NOT_FOUND: '*',
};
