export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  CATEGORY: '/categories/:categoryName',
  CATEGORY_SHIRTS: '/categories/shirts',
  CATEGORY_JEANS: '/categories/jeans',
  CATEGORY_SHOES: '/categories/shoes',
  CATEGORY_BAGS: '/categories/bags',
  LIVE: '/live',
  BUY_NOW: '/buy-now',
  ADDRESSES: '/addresses',
  NEW_ADDRESS: '/addresses/new',
  EDIT: '/addresses/edit/:id',
  LISTING_PAGE: `/listings/:id`,
  NEW_PRODUCT: `/new-product`,
  NOT_FOUND: '*',
};
